language: php

php:
   - '7.2'
   - '7.3'
   - '7.4snapshot'

install:
   - curl -s http://getcomposer.org/installer | php
   - php composer.phar install --dev --no-interaction --ignore-platform-reqs

script:
   - mkdir -p build/logs
   - PHP_CS_FIXER_IGNORE_ENV=1 ./vendor/bin/grumphp run

after_success:
   - travis_retry ./vendor/bin/php-coveralls -v