language: php

php:
   - '7.2'
   - '7.3'
   - nightly

install:
   - curl -s http://getcomposer.org/installer | php
   - php composer.phar install --dev --no-interaction --ignore-platform-reqs

script:
   - ./vendor/bin/grumphp run

after_success:
   - travis_retry ./vendor/bin/php-coveralls