language: php

php:
   - '7.2'
   - '7.3'
   - '7.4'
   - nightly
matrix:
 include:
   - php: '7.2'
     env: GRUMPHP=1 COVERAGE=1

install:
   - curl -s http://getcomposer.org/installer | php
   - php composer.phar install --dev --no-interaction --ignore-platform-reqs

script:
  - if [ "$GRUMPHP" = "1" ]; then ./vendor/bin/grumphp run; else composer run test; fi;

after_success:
   - if [ "$COVERAGE" = "1" ]; then ./vendor/bin/php-coveralls -v; fi;
